GET http://localhost:4000/health

###


POST http://localhost:4000/
Content-Type: application/json

{
    "name" : "Tamim",
    "country": "BD",
    "rank": 2
}

###

GET http://localhost:4000/


###

PATCH http://localhost:4000/ILLfqV3NC
Content-Type: application/json


{
    "name" : "Masrafi Bin Mortuza"
}

###

PUT http://localhost:4000/ILLfqV3NC
Content-Type: application/json


{
    "name" : "Masrafi",
    "country": "BD",
    "rank": 20
}

###

PUT http://localhost:4000/ILLfqV
Content-Type: application/json


{
    "name" : "Sakib",
    "country": "BD",
    "rank": 1
}

###

DELETE http://localhost:4000/ILLfqV3NC